### ISSUE TITLE
Build failed with an exception on Android device

### ISSUE THREAD

**Issue by niroshannrsh** [discourse/DiscourseMobile#19]
When following instruction for  setup application on android device.

Failure occur

  
![error](https://cloud.githubusercontent.com/assets/12439172/20649532/09a66248-b490-11e6-8db9-8a459f919949.png)

**Comment by SamSaffron** [comment]
Yeah this is tricky, we need some sort of dev setup script here @jjaffeux what are you doing on local?

**Comment by niroshannrsh** [comment]
I want to setup this app local machine ( Geny Motion Emulator )

**Comment by jjaffeux** [comment]
I was manually removing this block https://github.com/discourse/DiscourseMobile/blob/master/android/app/build.gradle#L100 when building for my device, we could probably figure out something better.

**Comment by jjaffeux** [comment]
This should now work.
