### ISSUE TITLE
Getting some weird rendering now that I upgraded react native

### ISSUE THREAD

**Issue by SamSaffron** [discourse/DiscourseMobile#20]
![image](https://cloud.githubusercontent.com/assets/5213/21513763/ad7fa6a2-cd10-11e6-9c5f-5dfc99baea4d.png)

Ouch 

@jjaffeux  care to have a look?

**Comment by SamSaffron** [comment]
simplest repro is to attempt to reorder rows

**Comment by SamSaffron** [comment]
note this all started cause I upgraded react ... :(

**Comment by SamSaffron** [comment]
weird, deleted my node packages and now it seems ok ... very strange

**Comment by SamSaffron** [comment]
yeah ... this latest version has some serious quirkiness going on... considering downgrading react a bit

**Comment by jjaffeux** [comment]
Hi, ok I see you decided to downgrade. Had a quick look on react-native’s github, didn't see anything.

We can wait a few days and then I will try to upgrade react-native and see if there's a problem with some libs.

**Comment by SamSaffron** [comment]
cool ... I think wait and see is fine, downgrading (and adding the animation library) seems to result in a pretty stable build
