### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by notrepo05** [discourse/DiscourseMobile#21]
After running yarn, manually removing [this block](https://github.com/discourse/DiscourseMobile/blob/master/android/app/build.gradle#L100) per [Issue 19](https://github.com/discourse/DiscourseMobile/issues/19) and running `react-native run-android`, I receive the error "cannot access AbstractSafeParcelable." So the compilation fails. 

I'd appreciate any direction you could provide. Thanks!

**Comment by SamSaffron** [comment]
Why are you closing this? I did mean to get back to doing another release
very soon. Sorry it has taken me soooooo long to deal with this.

**Comment by jjaffeux** [comment]
This should now be fixed.
