### ISSUE TITLE
Documentation on how to build (iOS or Android)

### ISSUE THREAD

**Issue by pmusaraj** [discourse/DiscourseMobile#22]
I would like to be able to fork this application so that I can release it as an application for my specific Discourse site. But I am having trouble just running the app locally on either ios or android. 

For ios, I'm getting this issue when running `react-native run-ios` (or running in Xcode): 

```
ld: library not found for -lRCTAnimation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

For android, for the equivalent `react-native run-android`: 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pmusaraj/Projects/DiscourseMobile/android/app/build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'MYAPP_RELEASE_STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

```

(I'm new to react-native, but a 'hello world' react native app runs fine for ios locally.)

**Comment by notrepo05** [comment]
Disclaimer: I haven't even managed to get DiscourseMobile to build yet.

I had a similar issue. I think a work-around for development purposes is to modify the build.gradle file as mentioned in [Issue 19](https://github.com/discourse/DiscourseMobile/issues/19).

Otherwise you might need to generate and setup your own keystore.

**Comment by pmusaraj** [comment]
I tried that, but it doesn't help, build fails again with 

```
> Could not get unknown property 'release' for SigningConfig container.
```

**Comment by notrepo05** [comment]
Don't comment out the `Release` itself. 

Try this: 
`
    signingConfigs {
        release {
     //       storeFile file(MYAPP_RELEASE_STORE_FILE)
     //       storePassword MYAPP_RELEASE_STORE_PASSWORD
     //       keyAlias MYAPP_RELEASE_KEY_ALIAS
     //       keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
`

**Comment by pmusaraj** [comment]
Thanks. That helps up to the `cannot access AbstractSafeParcelable` error you ran into [here](https://github.com/discourse/DiscourseMobile/issues/21).

**Comment by notrepo05** [comment]
It might be that removing the properties under release is causing this issue. If you find a work-around I'd really appreciate an update.

**Comment by pmusaraj** [comment]
On iOS, I managed to get past the build issues by doing the following: 
* follow instructions from this ReactNative issue: https://github.com/facebook/react-native/issues/11094#issuecomment-263240420
* change Bundle identifier to an App Id from your account, and change your Signing Team as well

**Comment by jjaffeux** [comment]
All of this should now work out of the box:

`react-native run-ios`
`react-native run-android`

Please reopen if you still have issues.

**Comment by theronic** [comment]
@jjaffeux what did you change to get it working? I'm getting the same linker error on another project.
