### ISSUE TITLE
Add apk's

### ISSUE THREAD

**Issue by alexgleason** [discourse/DiscourseMobile#28]
Hi, I'm interested to test this out but am not using Google Play or the Play Store. Typically I can find apk's for apps like this under the [releases section](https://github.com/discourse/DiscourseMobile/releases) of a github repo. Is this something you all would be willing to add? Thanks!

**Comment by SamSaffron** [comment]
am fine with this @jjaffeux  thoughts?

**Comment by jjaffeux** [comment]
Yes I can probably add this to the fastlane pipeline

**Comment by aaros-web** [comment]
Hi, I strongly support this request :)
When will apks be available ?

**Comment by jjaffeux** [comment]
Hey,

it's now available here: https://github.com/discourse/DiscourseMobile/tree/master/releases
