### ISSUE TITLE
[Android] Chrome alternatives

### ISSUE THREAD

**Issue by ildar** [discourse/DiscourseMobile#39]
Chrome requirement is a real surprise. I've seen no other Android app having this requirement.
Is it possible to use something other? FOSS is the preference. Possible options:
1. Firefox (there're pure FOSS builds)
2. Chromium
3. Lightning
4. AOSP WebView any Android has.
5. ...

**Comment by sideffect0** [comment]
The user should have the freedom to choose other browsers( instead of  "Chrome Stable" requirement)

**Comment by dfeyer** [comment]
Yes please, enforcing Google based browser for an opensource projet is NOT the way to go. Surveillance capitalist are good enough to push their stack in our face without us (dev) working for free for them (and sorry for the harsh tone, I LOVE discourse ... but this is not acceptable from my point of view).

**Comment by BrainBlasted** [comment]
Agreed on this. A WebView seems like the optimal way to go.

**Comment by pmusaraj** [comment]
This issue has been addressed in https://github.com/discourse/DiscourseMobile/commit/8bf665761744945e83a22ee766decb825e017721. If Chrome is not installed, the app will now fallback to any other installed browser.
