### ISSUE TITLE
App source should not be updated at play/app store?

### ISSUE THREAD

**Issue by asharamseervi** [discourse/DiscourseMobile#42]
Hello sam & community,

I reached here via https://discuss.reactjs.org/t/a-react-native-app-for-discourse/4634 and noticed that Discourse app started developing long back in Aug'16. Still, not much focus on this.

Even no one care to update source there at plat/app store to get updated with latest features. I can see many many commits after source updation at play store. If it is cold project, then any alternative available to achieve this with Discourse hosted forum?

![discourse-mobile-update](https://user-images.githubusercontent.com/5942572/41449722-70fbb6ac-7080-11e8-955b-e1bffde6b3b9.PNG)

**Comment by SamSaffron** [comment]
I am not following what the question is here, this is not a cold project, I use it daily.

**Comment by asharamseervi** [comment]
Thanks @SamSaffron. You noticed source apk updated last year ( December 17, 2017). Might it contains fewer features, that recently build by the community in few months.

I raised this question, because I want to make our community become mobile friendly and discuss things on mobile platforms. How can we use this app for particular discourse project hosted on the digital ocean. Community is currently discussing via browsers only. Can I customize the interface via theme/template/skin of app?
