### ISSUE TITLE
Start supporting Android

### ISSUE THREAD

**Issue by jjaffeux** [discourse/DiscourseMobile#5]
- [x] Make mvp working on android
- [x] Share shareable code (AFAIK, Home/Header and Site/Row should both work)
- [ ] Document how to get started on Android
- [ ] Make storybook work on android

Issues:
- [x] react-native-randombytes supports android only from version 2.x.x but there's also some bugs when trying to use version 2 : https://github.com/mvayngrib/react-native-randombytes/issues/5 We could fake it or use jsencrypt’s rng_get_byte for now, and replace it with randomBytes later
- [x] how to handle PushNotificationIOS ? Platform.OS === "ios" ?

**Comment by SamSaffron** [comment]
Left to do: 

[ ] Add crosswalk
[ ] Add push notification support via Firebase 
[ ] Add background updates
[ ] Add simulated push notifications for sites not supporting them

**Comment by SamSaffron** [comment]
I am closing this in favor of more specific items, android beta is now out :)
