### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [discourse/DiscourseMobile#51]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by gingerbeardman** [comment]
Could you please post some examples of your work? @mansya

**Comment by mansya** [comment]
example of my work like this [Link](https://www.behance.net/mansyaprime) and I will design the logo for this project as well as possible. I will do it now.

**Comment by gingerbeardman** [comment]
>example of my work like this [Link](https://www.behance.net/mansyaprime) and I will design the logo for this project as well as possible. I will do it now.

@mansya I'm just a user, I cannot give you permission to do the design

**Comment by SamSaffron** [comment]
@mansya not following, we already have the Discourse logo for the app?

**Comment by mansya** [comment]
ok if you already have a logo plan we can close this issues
