### ISSUE TITLE
Cannot connect to discourse instance - redirect back to app fails

### ISSUE THREAD

**Issue by MathiasRenner** [discourse/DiscourseMobile#59]
When I successfully authenticate for a discourse instance (an own one or even meta.discourse.org), I am redirected back to the home screen of the app **without being connected to the discourse instance**.

I am not sure if this is related to: https://github.com/discourse/DiscourseMobile/issues/27

This is a screenrecording of this issue: https://cloud.mathias-renner.com/s/X8WWc9T97iPSKsD

![image](https://user-images.githubusercontent.com/2377464/64926746-6ace9080-d801-11e9-923c-d3469eb18f90.png)

Why is this? Is it related to not having Google Apps on the device?

**Comment by pmusaraj** [comment]
Thanks @MathiasRenner, this was due to `android:launchMode:singleTop`, having that there forced the app to launch a new instance when returning from the browser. I'm pushing the beta now.
