### ISSUE TITLE
Implement Fastlane

### ISSUE THREAD

**Issue by jjaffeux** [discourse/DiscourseMobile#6]
We should use Fastlane (https://fastlane.tools/) as soon as we can to simplify the process of sending beta builds to beta testers.

Requirements:
- [ ] Apple account for this.
- [ ] Fabric account

**Comment by SamSaffron** [comment]
We are waiting on our DUNS number for the Discourse account, but fastlane is mostly implemented using my account

**Comment by jjaffeux** [comment]
Done.
