### ISSUE TITLE
bbs.onyx-international.com was not found!

### ISSUE THREAD

**Issue by asampal** [discourse/DiscourseMobile#60]
When I enter the subject hostname, I get a popup informing me that it can't be found. The Discourse instance is reachable on the desktop, though.

**Comment by pmusaraj** [comment]
Most likely your site is running in http. The app defaults to https. If you want to keep using http for your site, you will have to type `http://bbs.onyx-international.com`.

**Comment by asampal** [comment]
It's not my site, but in any case, I tried specifying it with http:// and got the same result.

**Comment by pmusaraj** [comment]
Using `http://bbs.onyx-international.com` works for me.
