### ISSUE TITLE
Create native RSA key generation for android

### ISSUE THREAD

**Issue by jjaffeux** [discourse/DiscourseMobile#9]
* https://github.com/SamSaffron/DiscourseMobile/commit/989c3a3eac40a5bc6b54dc700cccdf1fa7bbf62c
* https://developer.android.com/reference/java/security/KeyPairGenerator.html

**Comment by SamSaffron** [comment]
done per:

 https://github.com/SamSaffron/react-native-key-pair/commit/104cf12036562b6509cc6c198e151910dee0296e
